appId: com.jazzrihal.Fotuu
flows:
  - "auth/*"
  - "friends/*"
  - "moments/*"
  - "posts/*"
  - "profile/*"
executionOrder:
  continueOnFailure: false
  flowsOrder:
    - sign-in
    - sign-in-validation
    - sign-out
    - sign-up
    - view-profile
    - view-profile-post-detail
    - view-user-profile-post-detail
    - list
    - search
    - requests
    - feed
    - swipe-unfriend
    - save-recall-delete
    - open-profile-from-post
    - create-post
    - view-post-detail
    - save-post-locally
    - offline-post-fallback
